name: Chef Supermarket Action
description: Share cookbooks on the public supermarket
author: Álvaro Faúndez
branding:
  icon: share
  color: red
inputs:
  cookbook:
    description: The name of the cookbook. If not provided, it will be infered from the repository's name.
    required: false
  category:
    description: The supermarket category for your cookbook.
    required: false
    default: Other
  user:
    description: The supermaket user owner of the cookbook. if not provided, we will use the github user/organization's name.
    required: false
outputs:
  time:
    description: The time we greeted you
runs:
  using: docker
  image: Dockerfile
  env:
    COOKBOOK: ${{ inputs.cookbook }}
    CATEGORY: ${{ inputs.category }}
    USER: ${{ inputs.user }}
